name: 🤖 GPT Auto Code Push and Deploy

on:
  workflow_dispatch:

jobs:
  push_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Git config
        run: |
          git config --global user.name "gpt-auto"
          git config --global user.email "gpt-auto@openai.com"

      - name: Make Code Change
        run: |
          echo "// 🧠 GPT auto-push test: $(date)" >> index.js

      - name: Commit and Push
        run: |
          git add index.js
          git commit -m "🤖 GPT auto-push test"
          git push origin main
