name: Auto Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Trigger Render Deploy
        run: |
          curl -X POST https://api.render.com/deploy/srv-d1dcbbre5dus73b8ghqg?key=GSryi3m_mDs
