name: 🚀 Render Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add line to index.js
        run: |
          echo "// ✅ Auto-update test line: $(date)" >> index.js

      - name: Commit and push changes
        env:
          GH_PAT_PUSH: ${{ secrets.GH_PAT_PUSH }}
        run: |
          git config --global user.name "gpt-auto-commit"
          git config --global user.email "gpt@marketpulse.ai"
          git add index.js
          git commit -m "🤖 Auto-update: Append test line to index.js" || echo "No changes to commit."
          git push https://x-access-token:${GH_PAT_PUSH}@github.com/Fahil100/marketpulse-ai.git HEAD:main

      - name: Trigger Render Deploy
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys" \
          -H "Authorization: Bearer ${RENDER_API_KEY}" \
          -H "Content-Type: application/json" \
          -d '{}'
