name: 🚀 Render Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Deploy on Render
        env:
          RENDER_SERVICE_ID: $srv-d1dcbbre5dus73b8ghqg
          RENDER_API_KEY: $rnd_TsYbBgnN4LyOtFmQMEOKQlxXkssN 
        run: |
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{}'
